spring:
    datasource:
      url: jdbc:mysql://localhost:3306/my_web_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai
#      本地配置
#      url: jdbc:mysql://mysql:3306/my_web_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
    sql:
      init:
        mode: always  # 启动时执行 SQL 脚本
        encoding: UTF-8
        schema-locations: classpath:init.sql  # 建表脚本

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl