logging:
  level:
    org.example: info
    org.springframework: warn
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/my-web-app.log
    max-size: 10MB
    max-history: 7
